### ISSUE TITLE
Unable to bind to MusixMatch service on Android 5.0 (Service Intent must be explicit)

### ISSUE THREAD

**Issue by timusus** [musixmatch/android-lyrics-plugin-sdk#1]
In Android 5.0 Lollipop, Service Intents must now be explicit. Calling 'musixmatchLyricsConnector.doBindService()' throws an 'IllegalArgumentException':.

```
Caused by: java.lang.IllegalArgumentException: Service Intent must be explicit: Intent {     act=com.musixmatch.android.services.RemoteScrobblingService }
        at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1674)
        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1773)
        at android.app.ContextImpl.bindService(ContextImpl.java:1751)
        at android.content.ContextWrapper.bindService(ContextWrapper.java:538)
        at com.musixmatch.lyrics.musiXmatchLyricsConnector.doBindService(musiXmatchLyricsConnector.java:334)
```

Info from the Google developer docs: (http://developer.android.com/about/versions/android-5.0.html)

"If your app binds to a Service...

The Context.bindService() method now requires an explicit Intent, and throws an exception if given an implicit intent. To ensure your app is secure, use an explicit intent when starting or binding your Service, and do not declare intent filters for the service."

**Comment by timusus** [comment]
Nice :D
